import React, { useState } from 'react';
import { ToggleButton, ToggleButtonGroup, CardDeck } from 'react-bootstrap';
import Text from 'markov-chains-text';
import _ from 'lodash';
import { CssCard, ReactCard, NodeCard } from './Cards';
import { sampleText, baseText } from './sampleText';

function App() {
  const [value, setValue] = useState([1, 3]);
  const handleChange = (val) => setValue(val);

  const fakeText = new Text(baseText.concat(sampleText));
  const paragraph = _.times(4, (i) => fakeText.makeSentence(i));
  const regex = /\.,/gi;
  const nicerParagraph = paragraph.join().replace(regex, '. ');

  return (
    <>
      <div className="App">
        <ToggleButtonGroup type="checkbox" value={value} onChange={handleChange}>
          <ToggleButton variant="secondary" value={1}>Javascript</ToggleButton>
          <ToggleButton value={2}>React</ToggleButton>
          <ToggleButton variant="danger" value={3}>CSS</ToggleButton>
          <ToggleButton variant="info" value={4}>Node</ToggleButton>
        </ToggleButtonGroup>
        <div className="body">
          <h1 className="text-secondary">Aaron Mullan: Developer</h1>

          <CardDeck>
            <ReactCard />
            <CssCard />
            <NodeCard />
          </CardDeck>

          <h3 className="text-dark">Toggle options above for a fresh semi-coherent paragraph</h3>
          {/* eslint-disable-next-line max-len */}
          <div className="summary">
            <h5>
              Summary below is automatically generated by Markov chain from the finest cover letters avaialable for free on the internet. If I don&#39;t seem like the ideal candidate, simply select different options above
            </h5>
          </div>
          <div className="paragraph-container">
            { 1 && (

            <p className="paragraph">{nicerParagraph}</p>
            )}
          </div>
        </div>
      </div>
    </>
  );
}

export default App;
