import React from 'react';
import Text from 'markov-chains-text';
import _ from 'lodash';
import { sampleText, baseText } from './sampleText';

export default function Summary() {
  const fakeText = new Text(baseText.concat(sampleText));
  const paragraph = _.times(4, (i) => fakeText.makeSentence(i));
  const regex = /\.,/gi;
  const nicerParagraph = paragraph.join().replace(regex, '. ');

  return (
    <>
      <h3 className="text-dark">Toggle options above for a fresh semi-coherent paragraph</h3>
      <div className="summary">
        <h5>
          {/* eslint-disable-next-line max-len */}
          Summary below is automatically generated by Markov chain from the finest cover letters avaialable for free on the internet. If I don&#39;t seem like the ideal candidate, simply select different options above
        </h5>
      </div>
      <div className="paragraph-container">
        { 1 && (

        <p className="paragraph">{nicerParagraph}</p>
        )}
      </div>
    </>
  );
}
